export interface TseCandidate {
  seq: string;
  sqcand: string;
  n: string;
  nm: string;
  cc: string;
  nv?: string;
  e: string;
  st: string;
  dvt: string;
  vap: string;
  pvap: string;
}

// All 63 Deputies of Assembleia Legislativa da Bahia (ALBA) for 2026
export const CANDIDATES_2026_ESTADUAL: TseCandidate[] = [
  {
    "seq": "1",
    "sqcand": "2026-est-rc",
    "n": "43333",
    "nm": "ROBERTO CARLOS",
    "cc": "PV - Federação Brasil da Esperança (PT/PC do B/PV)",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "2",
    "sqcand": "2026-est-2",
    "n": "55456",
    "nm": "IVANA BASTOS",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "3",
    "sqcand": "2026-est-3",
    "n": "55000",
    "nm": "ALEX DA PIATÃ",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "4",
    "sqcand": "2026-est-4",
    "n": "55111",
    "nm": "ADOLFO MENEZES",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "5",
    "sqcand": "2026-est-5",
    "n": "44777",
    "nm": "MARCINHO OLIVEIRA",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "6",
    "sqcand": "2026-est-6",
    "n": "10133",
    "nm": "SAMUEL JUNIOR",
    "cc": "REPUBLICANOS",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "7",
    "sqcand": "2026-est-7",
    "n": "65500",
    "nm": "OLIVIA SANTANA",
    "cc": "PC do B",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "8",
    "sqcand": "2026-est-8",
    "n": "13444",
    "nm": "ROSEMBERG",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "9",
    "sqcand": "2026-est-9",
    "n": "15444",
    "nm": "ROGÉRIO ANDRADE",
    "cc": "MDB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "10",
    "sqcand": "2026-est-10",
    "n": "11777",
    "nm": "NILTINHO",
    "cc": "PP",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "11",
    "sqcand": "2026-est-11",
    "n": "13222",
    "nm": "ZÉ RAIMUNDO FONTES",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "12",
    "sqcand": "2026-est-12",
    "n": "11555",
    "nm": "NELSON LEAL",
    "cc": "PP",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "13",
    "sqcand": "2026-est-13",
    "n": "55444",
    "nm": "EURES RIBEIRO",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "14",
    "sqcand": "2026-est-14",
    "n": "10123",
    "nm": "JURAILTON SANTOS",
    "cc": "REPUBLICANOS",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "15",
    "sqcand": "2026-est-15",
    "n": "44000",
    "nm": "PEDRO TAVARES",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "16",
    "sqcand": "2026-est-16",
    "n": "44686",
    "nm": "KATIA OLIVEIRA",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "17",
    "sqcand": "2026-est-17",
    "n": "44111",
    "nm": "MARCELINHO VEIGA",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "18",
    "sqcand": "2026-est-18",
    "n": "10456",
    "nm": "JOSE DE ARIMATEIA",
    "cc": "REPUBLICANOS",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "19",
    "sqcand": "2026-est-19",
    "n": "13013",
    "nm": "OSNI",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "20",
    "sqcand": "2026-est-20",
    "n": "44100",
    "nm": "ALAN SANCHES",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "21",
    "sqcand": "2026-est-21",
    "n": "55255",
    "nm": "ANGELO CORONEL FILHO",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "22",
    "sqcand": "2026-est-22",
    "n": "44444",
    "nm": "SANDRO RÉGIS",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "23",
    "sqcand": "2026-est-23",
    "n": "45556",
    "nm": "TIAGO CORREIA",
    "cc": "PSDB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "24",
    "sqcand": "2026-est-24",
    "n": "11222",
    "nm": "EDUARDO SALLES",
    "cc": "PP",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "25",
    "sqcand": "2026-est-25",
    "n": "44123",
    "nm": "LUCIANO SIMÕES",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "26",
    "sqcand": "2026-est-26",
    "n": "43700",
    "nm": "VITOR BONFIM",
    "cc": "PV",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "27",
    "sqcand": "2026-est-27",
    "n": "22222",
    "nm": "VITOR AZEVEDO",
    "cc": "PL",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "28",
    "sqcand": "2026-est-28",
    "n": "55888",
    "nm": "CAFU BARRETO",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "29",
    "sqcand": "2026-est-29",
    "n": "55333",
    "nm": "EDUARDO ALENCAR",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "30",
    "sqcand": "2026-est-30",
    "n": "13000",
    "nm": "JUNIOR MUNIZ",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "31",
    "sqcand": "2026-est-31",
    "n": "43888",
    "nm": "MARQUINHO VIANA",
    "cc": "PV",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "32",
    "sqcand": "2026-est-32",
    "n": "44222",
    "nm": "MANUEL ROCHA",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "33",
    "sqcand": "2026-est-33",
    "n": "44144",
    "nm": "ROBINHO",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "34",
    "sqcand": "2026-est-34",
    "n": "44333",
    "nm": "JUNIOR NASCIMENTO",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "35",
    "sqcand": "2026-est-35",
    "n": "45555",
    "nm": "JORDAVIO RAMOS",
    "cc": "PSDB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "36",
    "sqcand": "2026-est-36",
    "n": "65888",
    "nm": "BOBÔ",
    "cc": "PC do B",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "37",
    "sqcand": "2026-est-37",
    "n": "40123",
    "nm": "SOANE GALVÃO",
    "cc": "PSB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "38",
    "sqcand": "2026-est-38",
    "n": "43444",
    "nm": "LUDMILLA FISCINA",
    "cc": "PV",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "39",
    "sqcand": "2026-est-39",
    "n": "11122",
    "nm": "HASSAN DE ZÉ COCÁ",
    "cc": "PP",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "40",
    "sqcand": "2026-est-40",
    "n": "15777",
    "nm": "MATHEUS DE GERALDO JÚNIOR",
    "cc": "MDB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "41",
    "sqcand": "2026-est-41",
    "n": "40100",
    "nm": "ANGELO ALMEIDA",
    "cc": "PSB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "42",
    "sqcand": "2026-est-42",
    "n": "13500",
    "nm": "ROBINSON",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "43",
    "sqcand": "2026-est-43",
    "n": "65333",
    "nm": "FABRÍCIO",
    "cc": "PC do B",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "44",
    "sqcand": "2026-est-44",
    "n": "13567",
    "nm": "FATIMA NUNES",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "45",
    "sqcand": "2026-est-45",
    "n": "45100",
    "nm": "PABLO ROBERTO ",
    "cc": "PSDB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "46",
    "sqcand": "2026-est-46",
    "n": "13123",
    "nm": "EUCLIDES FERNANDES",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "47",
    "sqcand": "2026-est-47",
    "n": "55777",
    "nm": "RICARDO RODRIGUES",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "48",
    "sqcand": "2026-est-48",
    "n": "12123",
    "nm": "EMERSON PENALVA",
    "cc": "PDT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "49",
    "sqcand": "2026-est-49",
    "n": "11111",
    "nm": "FELIPE DUARTE",
    "cc": "PP",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "50",
    "sqcand": "2026-est-50",
    "n": "65456",
    "nm": "ZÓ",
    "cc": "PC do B",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "51",
    "sqcand": "2026-est-51",
    "n": "13131",
    "nm": "MARIA DEL CARMEN",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "52",
    "sqcand": "2026-est-52",
    "n": "55789",
    "nm": "CLAUDIA OLIVEIRA",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "53",
    "sqcand": "2026-est-53",
    "n": "11011",
    "nm": "ANTÔNIO HENRIQUE JR.",
    "cc": "PP",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "54",
    "sqcand": "2026-est-54",
    "n": "51000",
    "nm": "BINHO GALINHA",
    "cc": "PATRIOTA",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "55",
    "sqcand": "2026-est-55",
    "n": "13113",
    "nm": "PAULO RANGEL",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "56",
    "sqcand": "2026-est-56",
    "n": "50150",
    "nm": "HILTON COELHO",
    "cc": "PSOL",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "57",
    "sqcand": "2026-est-57",
    "n": "20777",
    "nm": "LAERTE DO VANDO",
    "cc": "PSC",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "58",
    "sqcand": "2026-est-58",
    "n": "22333",
    "nm": "LEANDRO DE JESUS",
    "cc": "PL",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "59",
    "sqcand": "2026-est-59",
    "n": "70123",
    "nm": "PATRICK LOPES",
    "cc": "AVANTE",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "60",
    "sqcand": "2026-est-60",
    "n": "22522",
    "nm": "RAIMUNDINHO DA JR",
    "cc": "PL",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "61",
    "sqcand": "2026-est-61",
    "n": "22380",
    "nm": "DR. DIEGO CASTRO",
    "cc": "PL",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "62",
    "sqcand": "2026-est-62",
    "n": "77777",
    "nm": "LUCIANO ARAUJO",
    "cc": "SOLIDARIEDADE",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "63",
    "sqcand": "2026-est-63",
    "n": "77044",
    "nm": "PANCADINHA",
    "cc": "SOLIDARIEDADE",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  }
];

// All 40 Federal Deputies of Bahia for 2026 (including Vitor Bonfim 4070)
export const CANDIDATES_2026_FEDERAL: TseCandidate[] = [
  {
    "seq": "1",
    "sqcand": "2026-fed-vb",
    "n": "4070",
    "nm": "VITOR BONFIM",
    "cc": "PSB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "2",
    "sqcand": "2026-fed-2",
    "n": "5588",
    "nm": "OTTO FILHO",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "3",
    "sqcand": "2026-fed-3",
    "n": "4433",
    "nm": "ELMAR NASCIMENTO",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "4",
    "sqcand": "2026-fed-4",
    "n": "5500",
    "nm": "DIEGO CORONEL",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "5",
    "sqcand": "2026-fed-5",
    "n": "5510",
    "nm": "ANTONIO BRITO",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "6",
    "sqcand": "2026-fed-6",
    "n": "1144",
    "nm": "NETO CARLETTO",
    "cc": "PP",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "7",
    "sqcand": "2026-fed-7",
    "n": "2222",
    "nm": "ROBERTA ROMA",
    "cc": "PL",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "8",
    "sqcand": "2026-fed-8",
    "n": "1122",
    "nm": "CLAUDIO CAJADO",
    "cc": "PP",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "9",
    "sqcand": "2026-fed-9",
    "n": "1111",
    "nm": "MÁRIO NEGROMONTE JR",
    "cc": "PP",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "10",
    "sqcand": "2026-fed-10",
    "n": "1244",
    "nm": "LÉO PRATES",
    "cc": "PDT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "11",
    "sqcand": "2026-fed-11",
    "n": "4488",
    "nm": "DEPUTADO DAL",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "12",
    "sqcand": "2026-fed-12",
    "n": "5577",
    "nm": "GABRIEL NUNES",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "13",
    "sqcand": "2026-fed-13",
    "n": "4400",
    "nm": "PAULO AZI",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "14",
    "sqcand": "2026-fed-14",
    "n": "1555",
    "nm": "RICARDO MAIA",
    "cc": "MDB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "15",
    "sqcand": "2026-fed-15",
    "n": "1313",
    "nm": "JORGE SOLLA",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "16",
    "sqcand": "2026-fed-16",
    "n": "1323",
    "nm": "ZÉ NETO",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "17",
    "sqcand": "2026-fed-17",
    "n": "6565",
    "nm": "DANIEL",
    "cc": "PC do B",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "18",
    "sqcand": "2026-fed-18",
    "n": "6522",
    "nm": "ALICE PORTUGAL",
    "cc": "PC do B",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "19",
    "sqcand": "2026-fed-19",
    "n": "4545",
    "nm": "ADOLFO VIANA",
    "cc": "PSDB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "20",
    "sqcand": "2026-fed-20",
    "n": "1010",
    "nm": "MARCIO MARINHO",
    "cc": "REPUBLICANOS",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "21",
    "sqcand": "2026-fed-21",
    "n": "1301",
    "nm": "AFONSO FLORENCE",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "22",
    "sqcand": "2026-fed-22",
    "n": "5580",
    "nm": "SÉRGIO BRITO",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "23",
    "sqcand": "2026-fed-23",
    "n": "1322",
    "nm": "WALDENOR PEREIRA",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "24",
    "sqcand": "2026-fed-24",
    "n": "4040",
    "nm": "LÍDICE DA MATA",
    "cc": "PSB",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "25",
    "sqcand": "2026-fed-25",
    "n": "4343",
    "nm": "BACELAR",
    "cc": "PV",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "26",
    "sqcand": "2026-fed-26",
    "n": "4412",
    "nm": "ARTHUR MAIA",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "27",
    "sqcand": "2026-fed-27",
    "n": "5529",
    "nm": "PAULO MAGALHÃES",
    "cc": "PSD",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "28",
    "sqcand": "2026-fed-28",
    "n": "1023",
    "nm": "ALEX SANTANA",
    "cc": "REPUBLICANOS",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "29",
    "sqcand": "2026-fed-29",
    "n": "1300",
    "nm": "IVONEIDE CAETANO",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "30",
    "sqcand": "2026-fed-30",
    "n": "1361",
    "nm": "JOSEILDO RAMOS",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "31",
    "sqcand": "2026-fed-31",
    "n": "1115",
    "nm": "JOÃO LEÃO",
    "cc": "PP",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "32",
    "sqcand": "2026-fed-32",
    "n": "2238",
    "nm": "CAPITÃO ALDEN",
    "cc": "PL",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "33",
    "sqcand": "2026-fed-33",
    "n": "2288",
    "nm": "JOÃO CARLOS BACELAR",
    "cc": "PL",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "34",
    "sqcand": "2026-fed-34",
    "n": "1310",
    "nm": "VALMIR ASSUNÇÃO",
    "cc": "PT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "35",
    "sqcand": "2026-fed-35",
    "n": "1000",
    "nm": "ROGERIA SANTOS",
    "cc": "REPUBLICANOS",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "36",
    "sqcand": "2026-fed-36",
    "n": "4411",
    "nm": "LEUR LOMANTO JR",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "37",
    "sqcand": "2026-fed-37",
    "n": "4422",
    "nm": "JOSÉ ROCHA",
    "cc": "UNIÃO",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "38",
    "sqcand": "2026-fed-38",
    "n": "7000",
    "nm": "PASTOR SARGENTO ISIDÓRIO",
    "cc": "AVANTE",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "39",
    "sqcand": "2026-fed-39",
    "n": "1234",
    "nm": "FELIX  MENDONÇA",
    "cc": "PDT",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  },
  {
    "seq": "40",
    "sqcand": "2026-fed-40",
    "n": "1919",
    "nm": "RAIMUNDO COSTA",
    "cc": "PODE",
    "e": "n",
    "st": "Aguardando apuração",
    "dvt": "Válido",
    "vap": "0",
    "pvap": "0,00"
  }
];

// Official 2022 ALBA elected deputies with official TSE votes
export const CANDIDATES_2022_ESTADUAL: TseCandidate[] = [
  {
    "seq": "1",
    "sqcand": "50001607307",
    "n": "55456",
    "nm": "IVANA BASTOS",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "118417",
    "pvap": "1,49"
  },
  {
    "seq": "2",
    "sqcand": "50001607306",
    "n": "55000",
    "nm": "ALEX DA PIATÃ",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "114778",
    "pvap": "1,45"
  },
  {
    "seq": "3",
    "sqcand": "50001607292",
    "n": "55111",
    "nm": "ADOLFO MENEZES",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "107747",
    "pvap": "1,36"
  },
  {
    "seq": "4",
    "sqcand": "50001648293",
    "n": "44777",
    "nm": "MARCINHO OLIVEIRA",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "104969",
    "pvap": "1,32"
  },
  {
    "seq": "5",
    "sqcand": "50001619261",
    "n": "10133",
    "nm": "SAMUEL JUNIOR",
    "cc": "REPUBLICANOS",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "98914",
    "pvap": "1,25"
  },
  {
    "seq": "6",
    "sqcand": "50001606433",
    "n": "65500",
    "nm": "OLIVIA SANTANA",
    "cc": "PC do B",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "92559",
    "pvap": "1,17"
  },
  {
    "seq": "7",
    "sqcand": "50001606402",
    "n": "13444",
    "nm": "ROSEMBERG",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "90769",
    "pvap": "1,14"
  },
  {
    "seq": "8",
    "sqcand": "50001614699",
    "n": "15444",
    "nm": "ROGÉRIO ANDRADE",
    "cc": "MDB",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "89269",
    "pvap": "1,12"
  },
  {
    "seq": "9",
    "sqcand": "50001647048",
    "n": "11777",
    "nm": "NILTINHO",
    "cc": "PP",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "88313",
    "pvap": "1,11"
  },
  {
    "seq": "10",
    "sqcand": "50001606439",
    "n": "13222",
    "nm": "ZÉ RAIMUNDO FONTES",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "87695",
    "pvap": "1,10"
  },
  {
    "seq": "11",
    "sqcand": "50001647023",
    "n": "11555",
    "nm": "NELSON LEAL",
    "cc": "PP",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "81683",
    "pvap": "1,03"
  },
  {
    "seq": "12",
    "sqcand": "50001607295",
    "n": "55444",
    "nm": "EURES RIBEIRO",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "81508",
    "pvap": "1,03"
  },
  {
    "seq": "13",
    "sqcand": "50001619298",
    "n": "10123",
    "nm": "JURAILTON SANTOS",
    "cc": "REPUBLICANOS",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "80601",
    "pvap": "1,02"
  },
  {
    "seq": "14",
    "sqcand": "50001648327",
    "n": "44000",
    "nm": "PEDRO TAVARES",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "80490",
    "pvap": "1,01"
  },
  {
    "seq": "15",
    "sqcand": "50001648299",
    "n": "44686",
    "nm": "KATIA OLIVEIRA",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "80417",
    "pvap": "1,01"
  },
  {
    "seq": "16",
    "sqcand": "50001648309",
    "n": "44111",
    "nm": "MARCELINHO VEIGA",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "78456",
    "pvap": "0,99"
  },
  {
    "seq": "17",
    "sqcand": "50001619281",
    "n": "10456",
    "nm": "JOSE DE ARIMATEIA",
    "cc": "REPUBLICANOS",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "77995",
    "pvap": "0,98"
  },
  {
    "seq": "18",
    "sqcand": "50001606428",
    "n": "13013",
    "nm": "OSNI",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "77624",
    "pvap": "0,98"
  },
  {
    "seq": "19",
    "sqcand": "50001648281",
    "n": "44100",
    "nm": "ALAN SANCHES",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "77316",
    "pvap": "0,97"
  },
  {
    "seq": "20",
    "sqcand": "50001607294",
    "n": "55255",
    "nm": "ANGELO CORONEL FILHO",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "76455",
    "pvap": "0,96"
  },
  {
    "seq": "21",
    "sqcand": "50001648297",
    "n": "44444",
    "nm": "SANDRO RÉGIS",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "76361",
    "pvap": "0,96"
  },
  {
    "seq": "22",
    "sqcand": "50001613902",
    "n": "45556",
    "nm": "TIAGO CORREIA",
    "cc": "PSDB",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "71986",
    "pvap": "0,91"
  },
  {
    "seq": "23",
    "sqcand": "50001647028",
    "n": "11222",
    "nm": "EDUARDO SALLES",
    "cc": "PP",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "68673",
    "pvap": "0,86"
  },
  {
    "seq": "24",
    "sqcand": "50001648313",
    "n": "44123",
    "nm": "LUCIANO SIMÕES",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "68377",
    "pvap": "0,86"
  },
  {
    "seq": "25",
    "sqcand": "50001606406",
    "n": "43700",
    "nm": "VITOR BONFIM",
    "cc": "PV",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "68043",
    "pvap": "0,86"
  },
  {
    "seq": "26",
    "sqcand": "50001609449",
    "n": "22222",
    "nm": "VITOR AZEVEDO",
    "cc": "PL",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "67847",
    "pvap": "0,85"
  },
  {
    "seq": "27",
    "sqcand": "50001607305",
    "n": "55888",
    "nm": "CAFU BARRETO",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "67324",
    "pvap": "0,85"
  },
  {
    "seq": "28",
    "sqcand": "50001607296",
    "n": "55333",
    "nm": "EDUARDO ALENCAR",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "67265",
    "pvap": "0,85"
  },
  {
    "seq": "29",
    "sqcand": "50001606416",
    "n": "13000",
    "nm": "JUNIOR MUNIZ",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "67175",
    "pvap": "0,85"
  },
  {
    "seq": "30",
    "sqcand": "50001606436",
    "n": "43888",
    "nm": "MARQUINHO VIANA",
    "cc": "PV",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "66940",
    "pvap": "0,84"
  },
  {
    "seq": "31",
    "sqcand": "50001648303",
    "n": "44222",
    "nm": "MANUEL ROCHA",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "66445",
    "pvap": "0,84"
  },
  {
    "seq": "32",
    "sqcand": "50001648336",
    "n": "44144",
    "nm": "ROBINHO",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "65681",
    "pvap": "0,83"
  },
  {
    "seq": "33",
    "sqcand": "50001648300",
    "n": "44333",
    "nm": "JUNIOR NASCIMENTO",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "65423",
    "pvap": "0,82"
  },
  {
    "seq": "34",
    "sqcand": "50001613908",
    "n": "45555",
    "nm": "JORDAVIO RAMOS",
    "cc": "PSDB",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "64569",
    "pvap": "0,81"
  },
  {
    "seq": "35",
    "sqcand": "50001606413",
    "n": "65888",
    "nm": "BOBÔ",
    "cc": "PC do B",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "61469",
    "pvap": "0,77"
  },
  {
    "seq": "36",
    "sqcand": "50001605984",
    "n": "40123",
    "nm": "SOANE GALVÃO",
    "cc": "PSB",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "61399",
    "pvap": "0,77"
  },
  {
    "seq": "37",
    "sqcand": "50001606389",
    "n": "43444",
    "nm": "LUDMILLA FISCINA",
    "cc": "PV",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "60921",
    "pvap": "0,77"
  },
  {
    "seq": "38",
    "sqcand": "50001647026",
    "n": "11122",
    "nm": "HASSAN DE ZÉ COCÁ",
    "cc": "PP",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "60718",
    "pvap": "0,76"
  },
  {
    "seq": "39",
    "sqcand": "50001614689",
    "n": "15777",
    "nm": "MATHEUS DE GERALDO JÚNIOR",
    "cc": "MDB",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "60214",
    "pvap": "0,76"
  },
  {
    "seq": "40",
    "sqcand": "50001605968",
    "n": "40100",
    "nm": "ANGELO ALMEIDA",
    "cc": "PSB",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "59841",
    "pvap": "0,75"
  },
  {
    "seq": "41",
    "sqcand": "50001606417",
    "n": "13500",
    "nm": "ROBINSON",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "59435",
    "pvap": "0,75"
  },
  {
    "seq": "42",
    "sqcand": "50001606408",
    "n": "65333",
    "nm": "FABRÍCIO",
    "cc": "PC do B",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "57903",
    "pvap": "0,73"
  },
  {
    "seq": "43",
    "sqcand": "50001606388",
    "n": "43333",
    "nm": "ROBERTO CARLOS",
    "cc": "PV",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "57798",
    "pvap": "0,73"
  },
  {
    "seq": "44",
    "sqcand": "50001606437",
    "n": "13567",
    "nm": "FATIMA NUNES",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "56642",
    "pvap": "0,71"
  },
  {
    "seq": "45",
    "sqcand": "50001613913",
    "n": "45100",
    "nm": "PABLO ROBERTO ",
    "cc": "PSDB",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "55585",
    "pvap": "0,70"
  },
  {
    "seq": "46",
    "sqcand": "50001606438",
    "n": "13123",
    "nm": "EUCLIDES FERNANDES",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "55278",
    "pvap": "0,70"
  },
  {
    "seq": "47",
    "sqcand": "50001607297",
    "n": "55777",
    "nm": "RICARDO RODRIGUES",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "55031",
    "pvap": "0,69"
  },
  {
    "seq": "48",
    "sqcand": "50001620926",
    "n": "12123",
    "nm": "EMERSON PENALVA",
    "cc": "PDT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "51933",
    "pvap": "0,65"
  },
  {
    "seq": "49",
    "sqcand": "50001647074",
    "n": "11111",
    "nm": "FELIPE DUARTE",
    "cc": "PP",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "51187",
    "pvap": "0,64"
  },
  {
    "seq": "50",
    "sqcand": "50001606432",
    "n": "65456",
    "nm": "ZÓ",
    "cc": "PC do B",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "50893",
    "pvap": "0,64"
  },
  {
    "seq": "51",
    "sqcand": "50001606396",
    "n": "13131",
    "nm": "MARIA DEL CARMEN",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "50365",
    "pvap": "0,63"
  },
  {
    "seq": "52",
    "sqcand": "50001607301",
    "n": "55789",
    "nm": "CLAUDIA OLIVEIRA",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "49944",
    "pvap": "0,63"
  },
  {
    "seq": "53",
    "sqcand": "50001647027",
    "n": "11011",
    "nm": "ANTÔNIO HENRIQUE JR.",
    "cc": "PP",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "49882",
    "pvap": "0,63"
  },
  {
    "seq": "54",
    "sqcand": "50001610379",
    "n": "51000",
    "nm": "BINHO GALINHA",
    "cc": "PATRIOTA",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "49834",
    "pvap": "0,63"
  },
  {
    "seq": "55",
    "sqcand": "50001606403",
    "n": "13113",
    "nm": "PAULO RANGEL",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "49639",
    "pvap": "0,63"
  },
  {
    "seq": "56",
    "sqcand": "50001600622",
    "n": "50150",
    "nm": "HILTON COELHO",
    "cc": "PSOL",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "45491",
    "pvap": "0,57"
  },
  {
    "seq": "57",
    "sqcand": "50001604617",
    "n": "20777",
    "nm": "LAERTE DO VANDO",
    "cc": "PSC",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "44669",
    "pvap": "0,56"
  },
  {
    "seq": "58",
    "sqcand": "50001609456",
    "n": "22333",
    "nm": "LEANDRO DE JESUS",
    "cc": "PL",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "39206",
    "pvap": "0,49"
  },
  {
    "seq": "59",
    "sqcand": "50001603011",
    "n": "70123",
    "nm": "PATRICK LOPES",
    "cc": "AVANTE",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "35607",
    "pvap": "0,45"
  },
  {
    "seq": "60",
    "sqcand": "50001609434",
    "n": "22522",
    "nm": "RAIMUNDINHO DA JR",
    "cc": "PL",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "35188",
    "pvap": "0,44"
  },
  {
    "seq": "61",
    "sqcand": "50001609451",
    "n": "22380",
    "nm": "DR. DIEGO CASTRO",
    "cc": "PL",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "33827",
    "pvap": "0,43"
  },
  {
    "seq": "62",
    "sqcand": "50001620001",
    "n": "77777",
    "nm": "LUCIANO ARAUJO",
    "cc": "SOLIDARIEDADE",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "28412",
    "pvap": "0,36"
  },
  {
    "seq": "63",
    "sqcand": "50001620017",
    "n": "77044",
    "nm": "PANCADINHA",
    "cc": "SOLIDARIEDADE",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "27338",
    "pvap": "0,34"
  }
];

// Official 2022 Federal elected deputies with official TSE votes
export const CANDIDATES_2022_FEDERAL: TseCandidate[] = [
  {
    "seq": "1",
    "sqcand": "50001607228",
    "n": "5588",
    "nm": "OTTO FILHO",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "200909",
    "pvap": "2,52"
  },
  {
    "seq": "2",
    "sqcand": "50001634583",
    "n": "4433",
    "nm": "ELMAR NASCIMENTO",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "175439",
    "pvap": "2,20"
  },
  {
    "seq": "3",
    "sqcand": "50001607221",
    "n": "5500",
    "nm": "DIEGO CORONEL",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "171684",
    "pvap": "2,16"
  },
  {
    "seq": "4",
    "sqcand": "50001607229",
    "n": "5510",
    "nm": "ANTONIO BRITO",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "165386",
    "pvap": "2,08"
  },
  {
    "seq": "5",
    "sqcand": "50001621029",
    "n": "1144",
    "nm": "NETO CARLETTO",
    "cc": "PP",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "164655",
    "pvap": "2,07"
  },
  {
    "seq": "6",
    "sqcand": "50001609349",
    "n": "2222",
    "nm": "ROBERTA ROMA",
    "cc": "PL",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "160731",
    "pvap": "2,02"
  },
  {
    "seq": "7",
    "sqcand": "50001621019",
    "n": "1122",
    "nm": "CLAUDIO CAJADO",
    "cc": "PP",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "154098",
    "pvap": "1,94"
  },
  {
    "seq": "8",
    "sqcand": "50001621035",
    "n": "1111",
    "nm": "MÁRIO NEGROMONTE JR",
    "cc": "PP",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "147711",
    "pvap": "1,86"
  },
  {
    "seq": "9",
    "sqcand": "50001620881",
    "n": "1244",
    "nm": "LÉO PRATES",
    "cc": "PDT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "143763",
    "pvap": "1,81"
  },
  {
    "seq": "10",
    "sqcand": "50001634594",
    "n": "4488",
    "nm": "DEPUTADO DAL",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "140435",
    "pvap": "1,76"
  },
  {
    "seq": "11",
    "sqcand": "50001607226",
    "n": "5577",
    "nm": "GABRIEL NUNES",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "138448",
    "pvap": "1,74"
  },
  {
    "seq": "12",
    "sqcand": "50001634593",
    "n": "4400",
    "nm": "PAULO AZI",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "137383",
    "pvap": "1,73"
  },
  {
    "seq": "13",
    "sqcand": "50001614047",
    "n": "1555",
    "nm": "RICARDO MAIA",
    "cc": "MDB",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "136834",
    "pvap": "1,72"
  },
  {
    "seq": "14",
    "sqcand": "50001605359",
    "n": "1313",
    "nm": "JORGE SOLLA",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "128968",
    "pvap": "1,62"
  },
  {
    "seq": "15",
    "sqcand": "50001605365",
    "n": "1323",
    "nm": "ZÉ NETO",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "128439",
    "pvap": "1,61"
  },
  {
    "seq": "16",
    "sqcand": "50001605367",
    "n": "6565",
    "nm": "DANIEL",
    "cc": "PC do B",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "125374",
    "pvap": "1,58"
  },
  {
    "seq": "17",
    "sqcand": "50001605368",
    "n": "6522",
    "nm": "ALICE PORTUGAL",
    "cc": "PC do B",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "124358",
    "pvap": "1,56"
  },
  {
    "seq": "18",
    "sqcand": "50001613575",
    "n": "4545",
    "nm": "ADOLFO VIANA",
    "cc": "PSDB",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "123199",
    "pvap": "1,55"
  },
  {
    "seq": "19",
    "sqcand": "50001619869",
    "n": "1010",
    "nm": "MARCIO MARINHO",
    "cc": "REPUBLICANOS",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "118904",
    "pvap": "1,49"
  },
  {
    "seq": "20",
    "sqcand": "50001605378",
    "n": "1301",
    "nm": "AFONSO FLORENCE",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "118021",
    "pvap": "1,48"
  },
  {
    "seq": "21",
    "sqcand": "50001607223",
    "n": "5580",
    "nm": "SÉRGIO BRITO",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "116960",
    "pvap": "1,47"
  },
  {
    "seq": "22",
    "sqcand": "50001605361",
    "n": "1322",
    "nm": "WALDENOR PEREIRA",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "113110",
    "pvap": "1,42"
  },
  {
    "seq": "23",
    "sqcand": "50001606032",
    "n": "4040",
    "nm": "LÍDICE DA MATA",
    "cc": "PSB",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "112385",
    "pvap": "1,41"
  },
  {
    "seq": "24",
    "sqcand": "50001605351",
    "n": "4343",
    "nm": "BACELAR",
    "cc": "PV",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "110787",
    "pvap": "1,39"
  },
  {
    "seq": "25",
    "sqcand": "50001634596",
    "n": "4412",
    "nm": "ARTHUR MAIA",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "108672",
    "pvap": "1,37"
  },
  {
    "seq": "26",
    "sqcand": "50001607232",
    "n": "5529",
    "nm": "PAULO MAGALHÃES",
    "cc": "PSD",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "107093",
    "pvap": "1,35"
  },
  {
    "seq": "27",
    "sqcand": "50001619864",
    "n": "1023",
    "nm": "ALEX SANTANA",
    "cc": "REPUBLICANOS",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "106940",
    "pvap": "1,34"
  },
  {
    "seq": "28",
    "sqcand": "50001605353",
    "n": "1300",
    "nm": "IVONEIDE CAETANO",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "105885",
    "pvap": "1,33"
  },
  {
    "seq": "29",
    "sqcand": "50001605369",
    "n": "1361",
    "nm": "JOSEILDO RAMOS",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "104228",
    "pvap": "1,31"
  },
  {
    "seq": "30",
    "sqcand": "50001621034",
    "n": "1115",
    "nm": "JOÃO LEÃO",
    "cc": "PP",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "102376",
    "pvap": "1,29"
  },
  {
    "seq": "31",
    "sqcand": "50001609344",
    "n": "2238",
    "nm": "CAPITÃO ALDEN",
    "cc": "PL",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "95151",
    "pvap": "1,20"
  },
  {
    "seq": "32",
    "sqcand": "50001609371",
    "n": "2288",
    "nm": "JOÃO CARLOS BACELAR",
    "cc": "PL",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "90229",
    "pvap": "1,13"
  },
  {
    "seq": "33",
    "sqcand": "50001605371",
    "n": "1310",
    "nm": "VALMIR ASSUNÇÃO",
    "cc": "PT",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "90148",
    "pvap": "1,13"
  },
  {
    "seq": "34",
    "sqcand": "50001619841",
    "n": "1000",
    "nm": "ROGERIA SANTOS",
    "cc": "REPUBLICANOS",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "82012",
    "pvap": "1,03"
  },
  {
    "seq": "35",
    "sqcand": "50001634592",
    "n": "4411",
    "nm": "LEUR LOMANTO JR",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "82004",
    "pvap": "1,03"
  },
  {
    "seq": "36",
    "sqcand": "50001634584",
    "n": "4422",
    "nm": "JOSÉ ROCHA",
    "cc": "UNIÃO",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "78833",
    "pvap": "0,99"
  },
  {
    "seq": "37",
    "sqcand": "50001602958",
    "n": "7000",
    "nm": "PASTOR SARGENTO ISIDÓRIO",
    "cc": "AVANTE",
    "e": "s",
    "st": "Eleito por QP",
    "dvt": "Válido",
    "vap": "77164",
    "pvap": "0,97"
  },
  {
    "seq": "38",
    "sqcand": "50001620846",
    "n": "1234",
    "nm": "FELIX  MENDONÇA",
    "cc": "PDT",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "71774",
    "pvap": "0,90"
  },
  {
    "seq": "39",
    "sqcand": "50001615380",
    "n": "1919",
    "nm": "RAIMUNDO COSTA",
    "cc": "PODE",
    "e": "s",
    "st": "Eleito por média",
    "dvt": "Válido",
    "vap": "53486",
    "pvap": "0,67"
  },
  {
    "seq": "40",
    "sqcand": "2022-fed-vb",
    "n": "4070",
    "nm": "VITOR BONFIM",
    "cc": "PSB",
    "e": "n",
    "st": "Eleito Deputado Estadual em 2022 (43700)",
    "dvt": "Válido",
    "vap": "68043",
    "pvap": "0,86"
  }
];
